#!/usr/bin/perl -w

use strict;
use warnings;
use Switch;
use Getopt::Std;

my %opts = (t=>'0');
getopts('t:', \%opts);

my $usage = <<_EOUSAGE_;

Usage: DESeq2-utils <command> <arguments>
supports:

    annotation <deseq>     <qvalue>
    regulation <deseq>     <path>
    reshape    <abundance> <list>   <path>

_EOUSAGE_
;

if( ( scalar @ARGV) < 1){
    printf STDERR $usage;
    exit;

}

my %abundance_h   = (); 
my $cmd           = shift @ARGV; 

switch($cmd){

    case 'annotation'   { annotation_run(); };
    case 'regulation'   { regulation_run(); };
    case 'reshape'      { reshape_run(); };

}

exit;

sub annotation_run{

    if(@ARGV != 2){
        printf STDERR qq{\n[ERR] arguments number error!\n$usage};
        exit;
    }

    my ($deseq, $qvalue ) = @ARGV;
    print_tab( $deseq, $qvalue );

}

sub print_tab{
    
    my ($deseq, $qvalue)  = @_;
    open (DATA,  $deseq)  || die "[ERR]: can't open $deseq $!\n";

    my $t = <DATA>; chomp($t);
    print $t, "\tregulation\n";

    while (<DATA>) {
        
        chomp;
        my @its        = split /\t/, $_; 
        my $regulation = "";
        my $fc         = $its[-3]; 

        if( $its[-1] eq "NA" ||  $its[-1] > $qvalue ){
        	$regulation = "Not DE";	
        }else{
            $regulation = ( $fc > 0 ) ? "Up" : "Down";
        }
        
        print qq{$_\t$regulation\n};

    }
    close DATA;
}

sub regulation_run{

    if(@ARGV != 2){
        printf STDERR qq{\n[ERR] arguments number error!\n$usage};
        exit;
    }

    my ( $deseq, $path ) = @ARGV;
    regulation_list( $deseq, $path );

}


sub regulation_list {
    
    my ($deseq, $path)  = @_;
    open (DATA,  $deseq)  || die "[ERR]: can't open $deseq $!\n";
    <DATA>;
    my $t   = $opts{t};
    my %kv = ();
    while (<DATA>) {
        
        chomp;
        my @its        = split /\t/, $_; 
        next if(/^#/);

        if( $its[-1] ne "Not DE" && $its[-2] ne 'NA'){
            $kv{$its[0]} = $its[-2];
        }

    }
    close DATA;

    open (EXPORT,  qq{>$path}) || die "$! \n";
    my $cnt = 0;
    foreach my $f ( sort {$kv{$a} <=>  $kv{$b} } keys %kv) {
        
        last if($t != 0 && $cnt >= $t);
        printf EXPORT qq{$f\n};
        $cnt++;
    
    }
    close EXPORT;
}


sub reshape_run{

    if(@ARGV != 3){
        printf STDERR qq{\n[ERR] arguments number error!\n$usage};
        exit;
    }

    my ( $abundance, $list, $path ) = @ARGV;
    load_abundance( $abundance );
    feature_table( $list, $path );

}


sub load_abundance {
    
    my $abundance = shift;
    open (DATA,  $abundance)  || die "[ERR]: can't open $abundance $!\n";
    while (<DATA>) {
        
        chomp;
        my ($f, $d) = split /\t/, $_, 2;
        push @{$abundance_h{ $f }}, $d;

    }
    close DATA;
}


sub feature_table {
    
    my ($list, $path)  = @_;
    open (DATA,  $list)  || die "[ERR]: can't open $list $!\n";
    while (<DATA>) {      
        chomp;
        if(exists $abundance_h{$_} ){
            
            my $pp = $_; $pp =~s/\/|\]|\[|\)|\(|\,|\;|\]/_/g;
            $pp = substr($pp, 0, 100);

            open (EXPORT,  qq{>$path/$pp.txt}) || die "can't open $path/$pp.txt $! \n";
            print EXPORT   join("\n", @{$abundance_h{$_}});
            close EXPORT;
        }
    }
    close DATA;

}
